### PR TITLE
Fix converting datasets spanning the antimeridian

### LINKED ISSUE #6: Derastering _some_ datasets next to the antemeridian never terminate
I've created a minimal example here https://github.com/JayKickliter/deraster

Derastering the SRTM in the above example seems to never terminate. Others SRTMs along the antimeridian fail to terminate when given a specific resolution, but will terminate fairly quickly if derastering at their "natural" resolution. All other 26,000ish SRTM files deraster fine no matter what resolution I specify.

### PR DESCRIPTION
**Pull request by nmandery**
Fix converting datasets spanning the antimeridian by splitting and normalizing tiles before generating cells from them.

Fixes #6

### CODE REVIEW

File: src/array.rs [hunk 1]
```diff
@@ -320,36 +321,50 @@ where
...
-            }
-        };
-        if let Some(value) = arr.get(arr_coord) {
-            if let Some(nodata) = nodata_value {
-                if nodata == value {
-                    continue;
+
+    for splitted_window_box in split_rect_at_antimeridian(window_box) {
+        // h3 is only defined within -180 ... 180, so all boxes after the antimeridian split should be
+        // in this range.
```
Comment (grim7reaper) [inline src/array.rs:327]: Indeed, and I should probably check this when a new geometry is created!

Ideally it should even be checked at the level of the `LatLng` type, but internally it sometimes goes out of this range so it's a bit more complex to pull off.

Comment (nmandery) [reply src/array.rs:327]: I would not worry too much about checking this within h3o. It would be worth mentioning it in the docs - maybe on the `LatLng`  type.

I suppose tackling it a type-safe way would require having a second LatLng-like type for internal use. That one then could allow going out of this range.
